modLoader="javafml"
loaderVersion="${loader_version_range}"
license="GPL"

[[mods]]
modId="momotinker"
version="1.0.0"
displayName="Momotinker"
authors="momosensei"
description='''Momotinker.'''

[[dependencies.momotinker]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.momotinker]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"